name: CI

defaults:
  run:
    shell: bash
    working-directory: MovieDatabase

on:
  push:
    branches:
      - $default_branch
  pull_request:
    branches:
      - $default_branch

jobs:
  build-and-test:
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Install bundler
        run: | 
          gem install bundler --no-document
          bundle config set deployment 'true';
          bundle config path vendor/bundle;
          bundle install

      - name: Run tests
        run: bundle exec fastlane test